apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: this-is-my-kingdom-come
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx