apiVersion: v1
kind: Namespace
metadata:
  name: secured
  labels:
    kubernetes.io/metadata.name: secured
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-deny-pod-communication
  namespace: secured
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow ingress traffic (adjust labels/namespaces to match your setup)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx  # Replace with your ingress namespace
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx       # Replace with your ingress pod labels
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
    # Allow Cert Manager challenges (if using HTTP01)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cert-manager    # Replace with your cert-manager namespace
          podSelector:
            matchLabels:
              app.kubernetes.io/name: cert-manager         # Replace with your cert-manager pod labels
      ports:
        - protocol: TCP
          port: 80
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53